nelmio_cors:
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/jwt_verify':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/get_user':
            allow_origin: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            max_age: 3600