
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: []
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
        hosts: []
        origin_regex: false

    paths:
        '^/api/':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/jwt_verify':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/get_user':
            allow_origin: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/recipes':
            allow_origin: [ '*' ]
            allow_methods: [ 'POST', 'PUT', 'GET', 'DELETE', 'OPTIONS' ]
            allow_headers: [ 'Content-Type', 'Authorization' ]
            max_age: 3600
